"""empty message

Revision ID: 4ed9c4b2d485
Revises: 309268c6a437
Create Date: 2018-10-27 00:37:33.624268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed9c4b2d485'
down_revision = '309268c6a437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('prenom', sa.String(length=150), nullable=False),
    sa.Column('date_naissance', sa.String(length=150), nullable=False),
    sa.Column('situation_matrimonial', sa.String(length=150), nullable=False),
    sa.Column('entreprise', sa.String(length=150), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('forme_juridique', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('fonction', sa.String(), nullable=False),
    sa.Column('domaine_activite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adresse'),
    sa.UniqueConstraint('date_naissance'),
    sa.UniqueConstraint('domaine_activite'),
    sa.UniqueConstraint('entreprise'),
    sa.UniqueConstraint('fonction'),
    sa.UniqueConstraint('forme_juridique'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude'),
    sa.UniqueConstraint('nom'),
    sa.UniqueConstraint('prenom'),
    sa.UniqueConstraint('situation_matrimonial')
    )
    op.drop_table('categories')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('client')
    # ### end Alembic commands ###
